name: dailystep
description: "A new Flutter project."

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  freezed: ^2.5.7
  nav: ^1.4.3
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  dio: ^5.7.0
  table_calendar: ^3.1.2
  scroll_date_picker: ^3.8.0
  go_router: ^14.3.0
  flutter_localization: ^0.2.2
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.0.2
  image_picker: ^1.1.2
  package_info_plus: ^8.1.0
  flutter_svg: ^1.0.1

  #login
  flutter_naver_login: ^2.0.0
  google_sign_in: ^6.2.1
  kakao_flutter_sdk: ^1.9.6
  url_launcher: ^6.3.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter_local_notifications: 18.0.1
  shared_preferences: ^2.3.5
  flutter_image_compress: ^2.4.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^5.0.0
  freezed_annotation: ^2.4.4
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/
    - assets/splash/
    - assets/auth/
  fonts:
    - family: Suit
      fonts:
        - asset: assets/fonts/SUIT-Medium.ttf
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
