name: dailystep
description: "A new Flutter project."

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #util
  velocity_x: ^4.2.1
  freezed: ^2.5.7

  nav: ^1.4.3
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.2
  dio: ^5.7.0
  table_calendar: ^3.1.2
  go_router: ^14.3.0
  flutter_localization: ^0.2.2
  flutter_secure_storage: ^9.2.2

  #login
  flutter_naver_login: ^2.0.0
  google_sign_in: ^6.2.0
  kakao_flutter_sdk: ^1.9.6
  package_info_plus: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  lints: ^5.0.0
  freezed_annotation: ^2.4.4
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
