import 'challenge_model.dart';

final List<Challenge> dummyChallenges = [
  const Challenge(
    id: 0,
    title: '30-Day Fitness Challenge',
    startDate: '2024-01-01',
    period: 7,
    progress: 3,
    isCompleted: false,
    repeat: 3,
    isAlarm: true,
    alarmTime: '07:00',
    alarmDate: '2024-01-01',
    category: 'Health',
    note: 'Morning workout',
  ),
  const Challenge(
    id: 1,
    title: 'Read 12 Books in a Year',
    startDate: '2024-02-01',
    period: 14,
    progress: 5,
    isCompleted: false,
    repeat: 3,
    isAlarm: false,
    category: 'Education',
    note: 'Focus on personal development books',
  ),
  const Challenge(
    id: 2,
    title: 'Meditate Daily for 1 Month',
    startDate: '2024-03-01',
    period: 21,
    progress: 4,
    isCompleted: true,
    repeat: 1,
    isAlarm: true,
    alarmTime: '06:00',
    alarmDate: '2024-03-01',
    category: 'Mindfulness',
    note: 'Morning meditation routine',
  ),
  const Challenge(
    id: 3,
    title: 'Learn Flutter Basics',
    startDate: '2024-04-01',
    period: 14,
    progress: 10,
    isCompleted: false,
    repeat: 2,
    isAlarm: true,
    alarmTime: '08:00',
    alarmDate: '2024-04-01',
    category: 'Programming',
    note: 'Follow online course for Flutter basics',
  ),
  const Challenge(
    id: 4,
    title: 'No Sugar for 1 Week',
    startDate: '2024-05-01',
    period: 14,
    progress: 7,
    isCompleted: true,
    repeat: 1,
    isAlarm: false,
    category: 'Health',
    note: 'Stick to a healthy diet',
  ),
];
